# Generated by Django 2.2.4 on 2019-08-18 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='description',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='note',
            name='reminder',
        ),
    ]
