# Generated by Django 2.2.4 on 2019-08-19 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_auto_20190818_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='deactivate',
            field=models.BooleanField(default=False),
        ),
    ]
